### ISSUE TITLE
Error in EXP Calculation

### ISSUE THREAD

**Issue by keoShine** [belthesar/MalmstoneXPCalculator#4]
There appears to be an error in script.js on Line 62 that feeds the Goal Level element into both the Goal Level _and_ the Current Progress; e.g., if the goal level is 25, then the calculator also always treats the Current Progress as 25 exp towards the next level rather than what's actually in that field..

![image](https://github.com/user-attachments/assets/2d9121ae-488e-4ce9-a6ae-8420946b33a6)

See below, showing that I have 6,125 entered as Current Progress, but the calculator returns that I need 29,975 exp (30,000 between 21 and 25 minus the 25 exp that it's taking out by subtracting the Goal Level):
![image](https://github.com/user-attachments/assets/30d9a38f-9dc8-4ec4-856f-da516edbc5e6)

**Comment by belthesar** [comment]
Hiya! Thanks for reporting this issue! I'll have a look to see what's going on here. 

Wow, a fat finger that has been awful for quite a while, haha. Thanks for finding this! A fix should be live shortly!
